apiVersion: v1
kind: Service
metadata:
  name: bzzz-api
  namespace: default
spec:
  selector:
    app: bzzz-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer