apiVersion: v1
kind: Service
metadata:
  name: bzzz-api
  namespace: default
  annotations:
    service.beta.kubernetes.io/do-loadbalancer-protocol: "https"
    service.beta.kubernetes.io/do-loadbalancer-algorithm: "least_connections"
    service.beta.kubernetes.io/do-loadbalancer-tls-ports: "443"
    service.beta.kubernetes.io/do-loadbalancer-certificate-id: "7fe04fc7-d6fa-47e6-932e-4657f79e471c"
    service.beta.kubernetes.io/do-loadbalancer-redirect-http-to-https: "true"
spec:
  selector:
    app: bzzz-api
  ports:
  - name: https
    protocol: TCP
    port: 443
    targetPort: 8080
  type: LoadBalancer